name: wl-clip
version: '2.2'
summary: wl-clipboard - command-line copy/paste utilities for Wayland
description: |
  If you want this snap to use well known command names system-wide, run as a root user:

  snap alias wl-clip.copy wl-copy  
  snap alias wl-clip.paste wl-paste
source-code: https://github.com/iomezk/snap-wl-clip
license: GPL-3.0+
base: core22
confinement: strict
grade: stable

apps:
  copy:
    command-chain:
    - wrapper
    command: bin/wl-copy
    plugs:
    - wayland
  paste:
    command-chain:
    - wrapper
    command: bin/wl-paste
    plugs:
    - wayland

environment:
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
  wl-clipboard:
    source: https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v2.2.0.tar.gz
    source-checksum: sha256/414005cfa229d0e54f89a0d9a8473938e4c29adc21a9e556847a4d44ad508874
    source-type: tar
    plugin: meson
    build-packages:
    - meson
    - pkg-config
    - libwayland-dev
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    prime:
    - bin/
