name: wl-clip
adopt-info: wl-clipboard
summary: wl-clipboard - command-line copy/paste utilities for Wayland
description: |
  If you want this snap to use well known command names system-wide, run as a root user:

  snap alias wl-clip.copy wl-copy  
  snap alias wl-clip.paste wl-paste
source-code: https://github.com/iomezk/snap-wl-clip
license: GPL-3.0+
base: core22
confinement: strict
grade: stable

apps:
  copy:
    command: bin/wl-copy
    plugs:
    - wayland
  paste:
    command: bin/wl-paste
    plugs:
    - wayland

environment:
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  wl-clipboard:
    source: https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v2.2.1.tar.gz
    source-checksum: sha256/6eb8081207fb5581d1d82c4bcd9587205a31a3d47bea3ebeb7f41aa1143783eb
    source-type: tar
    plugin: meson
    build-packages:
    - jq
    - meson
    - pkg-config
    - libwayland-dev
    - wayland-protocols
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/fixed-runtime-dir.patch"
    override-build: |
      craftctl default
      craftctl set "version=$(jq -r .version meson-info/intro-projectinfo.json)"
    prime:
    - bin/
